const val kotlinVersion = "1.6.10"
const val junit5Version = "5.7.2"
const val hiltVersion = "2.41"

const val KotlinStdLib = "org.jetbrains.kotlin:kotlin-stdlib:$kotlinVersion"
const val JunitJupyter = "org.junit.jupiter:junit-jupiter:$junit5Version"
const val JunitVintageEngine = "org.junit.vintage:junit-vintage-engine:$junit5Version"
const val Junit4 = "junit:junit:4.13.2"
const val MockK = "io.mockk:mockk:1.12.3"
const val Truth = "com.google.truth:truth:1.1.3"
const val CoroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
const val CoroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"
const val CoroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.6.4"

const val HiltCore = "com.google.dagger:hilt-core:$hiltVersion"
const val HiltAndroid = "com.google.dagger:hilt-android:$hiltVersion"
const val HiltKapt = "com.google.dagger:hilt-android-compiler:$hiltVersion"
