name: Build

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'
      - uses: android-actions/setup-android@v2
      - name: gradlew 권한 설정
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
